rentyapp/board/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from board import views

urlpatterns = [
    url(r'^login/?$', views.login),
    url(r'^main/?$', views.dashboard),
    url(r'^orders/?$', views.order_list),
    url(r'^charges/?$', views.charges_list),
    url(r'^orders/charges/?$', views.order_charges_list),
    url(r'^users/?$', views.user_list),
    url(r'^property/?$', views.property_list),
    url(r'^resident/?$', views.resident_list),
    url(r'^contract/?$', views.contract_list),
    url(r'^logout/?$', views.logout),
    url(r'^service/types/?$', views.service_type_list),
    url(r'^payment/property/?$', views.payment_property_list),
    url(r'^users/edit/?$', views.edit_profile),
    url(r'^users/add/?$', views.add_profile),
    url(r'^users/delete/(?P<user_id>[\w\-]+)/?$', views.delete_user),
    url(r'^orders/edit/(?P<order_id>[\w\-]+)/?$', views.edit_order),#{10}
    url(r'^charges/edit/(?P<charge_id>[\w\-]+)/?$', views.edit_charge),#{10}
    url(r'^orders/charges/edit/(?P<charge_id>[\w\-]+)/?$', views.edit_order_charge),#{10}
    url(r'^users/edit/(?P<user_id>[\w\-]+)/?$', views.edit_profiles),
    url(r'^property/edit/(?P<property_id>[\w\-]+)/?$', views.edit_property),
    url(r'^service/types/edit/(?P<service_id>[\w\-]+)/?$', views.edit_service),
    url(r'^resident/edit/(?P<resident_id>[\w\-]+)/?$', views.edit_residents),
    url(r'^contract/edit/(?P<contract_id>[\w\-]+)/?$', views.edit_contract),
    url(r'^service/types/add/?$', views.add_service),
    url(r'^payment/download/xls/?$', views.excel_bank_export),
    # (?P<path>.*)$

]

rentyapp/rentyapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^board/', include('board.urls')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    #url(r'^explorer/', include('explorer.urls')),
]

rentyapp/board/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    available = models.NullBooleanField()

    class Meta:
        managed = False
        db_table = 'categories'

    def __str__(self):
        return '%s' % (self.name)


class Charges(models.Model):
    amount = models.IntegerField(blank=True, null=True)
    contract = models.ForeignKey('Contracts', models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=False)
    status = models.NullBooleanField(default=False)
    current_value = models.FloatField(blank=True, null=True, default=0)
    readjustment = models.NullBooleanField(default=False)
    pay_date = models.DateField(auto_now_add=False)

    class Meta:
        managed = False
        db_table = 'charges'

    def __str__(self):
        return '%s' % (self.contract)


class Communes(models.Model):
    name = models.CharField(max_length=1, blank=True, null=True)
    region = models.ForeignKey('Regions', models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'communes'

    def __str__(self):
        return self.name


class Contracts(models.Model):
    fare_type = models.CharField(max_length=100, blank=True, null=True)
    amount = models.IntegerField(blank=True, null=True)
    pay_day = models.IntegerField(blank=True, null=True)
    start_rent = models.DateField(blank=True, null=True)
    end_rent = models.DateField(blank=True, null=True)
    contract_period = models.CharField(max_length=100, blank=True, null=True)
    status = models.NullBooleanField(default=False)
    automatic_renewal = models.NullBooleanField()
    pdf = models.CharField(max_length=100, blank=True, null=True)
    ipc_readjustment = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=False)
    property = models.ForeignKey('Properties', models.DO_NOTHING, blank=True, null=True)
    resident = models.ForeignKey('Residents', models.DO_NOTHING, blank=True, null=True)
    clp_to_uf = models.FloatField(blank=True, null=True)
    readjustment = models.NullBooleanField(default=False)

    def __str__(self):
        return '%s' % (self.fare_type)

    class Meta:
        managed = False
        db_table = 'contracts'





class Fixes(models.Model):
    description = models.TextField(blank=True, null=True)
    amount = models.IntegerField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    status = models.NullBooleanField()
    deducted = models.NullBooleanField()
    contract = models.ForeignKey(Contracts, models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    title = models.CharField(max_length=1, blank=True, null=True)
    response = models.TextField(blank=True, null=True)
    charge = models.ForeignKey(Charges, models.DO_NOTHING, blank=True, null=True)
    kind = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'fixes'

    def __str__(self):
        return '%s' % (self.contract)


class OrderCharges(models.Model):
    charge = models.ForeignKey(Charges, models.DO_NOTHING, blank=True, null=True)
    order = models.ForeignKey('Orders', models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField(auto_created=True)
    updated_at = models.DateTimeField(auto_now_add=False)
    amount = models.IntegerField(blank=True, null=True,default=0)

    class Meta:
        managed = False
        db_table = 'order_charges'

    def __str__(self):
        return '%s' % (self.order)


class Orders(models.Model):
    provider = models.CharField(max_length=100, blank=True, null=True)
    status = models.NullBooleanField(default=False)
    amount = models.IntegerField(blank=True, null=True, default=0)
    file = models.CharField(max_length=100, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_created=False)
    resident_id = models.IntegerField(blank=True, null=True, default=0)
    contract_id = models.IntegerField(blank=True, null=True, default=0)
    code = models.IntegerField(blank=True, null=True)
    tbk_accounting_date = models.CharField(max_length=1, blank=True, null=True)
    tbk_buy_order = models.CharField(max_length=100, blank=True, null=True)
    tbk_cardnumber = models.CharField(max_length=100, blank=True, null=True)
    tbk_commerce_code = models.CharField(max_length=100, blank=True, null=True)
    tbk_authorization_code = models.CharField(max_length=100, blank=True, null=True)
    tbk_payment_type_code = models.CharField(max_length=100, blank=True, null=True)
    tbk_responde_code = models.CharField(max_length=100, blank=True, null=True)
    tbk_transaction_date = models.CharField(max_length=100, blank=True, null=True)
    tbk_vci = models.CharField(max_length=100, blank=True, null=True)
    tbk_amount = models.CharField(max_length=100, blank=True, null=True)
    token = models.CharField(max_length=100, blank=True, null=True)
    tbk_shares = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'orders'

    def __str__(self):
        return '%s' % (self.code)


class Owners(models.Model):
    name = models.CharField(max_length=1, blank=True, null=True)
    last_name = models.CharField(max_length=1, blank=True, null=True)
    rut = models.CharField(max_length=1, blank=True, null=True)
    agent = models.NullBooleanField()
    phone = models.CharField(max_length=1, blank=True, null=True)
    address = models.CharField(max_length=1, blank=True, null=True)
    code = models.CharField(max_length=1, blank=True, null=True)
    user = models.ForeignKey('Users', models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'owners'

    def __str__(self):
        return "{0} {1}".format(self.name, self.last_name)

class Properties(models.Model):

    category = models.ForeignKey(Categories, models.DO_NOTHING, default=0)
    region = models.ForeignKey('Regions', models.DO_NOTHING, default=0)
    commune = models.ForeignKey(Communes, models.DO_NOTHING, default=0)
    street = models.CharField(max_length=100,default=0)
    street_number = models.CharField(max_length=10,default=0)
    property_number = models.CharField(max_length=10,default=0)
    size = models.IntegerField(default=0)
    image = models.CharField(max_length=250, default='image.png')
    name_concierge = models.CharField(max_length=100)
    phone_concierge = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=False)
    owner = models.ForeignKey(Owners, models.DO_NOTHING, default=0)

    class Meta:
        managed = False
        db_table = 'properties'

    def __str__(self):
        return '%s - P/N: (%s)' % (self.owner, self.property_number)




class PaymentProperties(models.Model):
    property = models.ForeignKey('Properties', models.DO_NOTHING, blank=True, null=True)
    bank = models.CharField(max_length=100, blank=True, null=True)
    account_type = models.CharField(max_length=100, blank=True, null=True)
    account_number = models.CharField(max_length=100, blank=True, null=True)
    name_holder = models.CharField(max_length=100, blank=True, null=True)
    rut_holder = models.CharField(max_length=20, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=False)
    email = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'payment_properties'

    def __str__(self):
        return '%s' % (self.property)


class PreUsers(models.Model):
    name = models.CharField(max_length=1, blank=True, null=True)
    last_name = models.CharField(max_length=1, blank=True, null=True)
    email = models.CharField(max_length=1, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'pre_users'

    def __str__(self):
        return "{0} {1}".format(self.name, self.last_name)



class Regions(models.Model):
    number = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'regions'

    def __str__(self):
        return '%s' % (self.name)


class Residents(models.Model):

    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    rut = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    score = models.IntegerField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

rentyapp/templates/v3/dashboard/order_charges/order_charges_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png"
          href="/static/v3/media/website/logo-solo-cb7b48d8befc7c0b5d7f7bd44c8d69ffeed06130a5646ea7a09bb0b57a29b1ed.png"
          sizes="16x16">

    <title>Dashboard Renty</title>
    {% include "v3/dashboard/imports/css.html" %}
    <!-- Custom styles for this template -->

</head>

<body>
{% csrf_token %}
{% include "v3/dashboard/imports/header.html" %}

<div class="container-fluid">
    <div class="row">

        {% include "v3/dashboard/imports/menu.html" %}

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3 mt-4" role="main">

            <ol class="breadcrumb">
                <li class="breadcrumb-item">Order Charges</li>
                <li class="breadcrumb-item active">Modify / ID:{{charge_object.id}}</li>
            </ol>
            {% if saved %}
            <div class="alert alert-success" role="alert">
                Order Charge "{{charge_object.id}}" information was modified, correctly !
            </div>

            {% endif %}

            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% for error in field.errors %}
                {{error}}<BR>
                {% endfor %}
                {% endfor %}
            </div>
            {% endif %}


            <!-- Profile Edit -->

            <table width="605" border="0" cellspacing="0" cellpadding="0" class="table table-bordered table-striped">
                <tbody>
                <tr>
                    <td width="605">
                        <strong>Order Charge Information</strong>
                    </td>
                </tr>
                <tr>
                    <td>

                        <div class="container">
                            <form method="post">
                                {% csrf_token %}

                                {% for field in form %}

                                <!-- Field  {{ field.label }} -->
                                <div class="form-group row">
                                    <label for="{{ field.auto_id }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                                    <div class="col-sm-10">
                                        {{ field }}
                                    </div>
                                </div>

                                {% endfor %}

                                <div class="form-group row">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-success">Save</button>
                                        <a href="/board/charges/" class="btn btn-light">Cancel</a>
                                    </div>

                                </div>


                            </form>
                        </div>

                    </td>
                </tr>


                </tbody>
            </table>


            <!-- -->

        </main>
    </div>
</div>

{% include "v3/dashboard/imports/js.html" %}

<script>

    $(function() {

         $( "#id_pay_date" ).datepicker({ dateFormat: 'yy-mm-dd' });


    });


</script>


</body>
</html>