rentyapp/board/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from board import views

urlpatterns = [
    url(r'^login/?$', views.login),
    url(r'^main/?$', views.dashboard),
    url(r'^orders/?$', views.order_list),
    url(r'^charges/?$', views.charges_list),
    url(r'^orders/charges/?$', views.order_charges_list),
    url(r'^users/?$', views.user_list),
    url(r'^property/?$', views.property_list),
    url(r'^resident/?$', views.resident_list),
    url(r'^contract/?$', views.contract_list),
    url(r'^logout/?$', views.logout),
    url(r'^service/types/?$', views.service_type_list),
    url(r'^payment/property/?$', views.payment_property_list),
    url(r'^users/edit/?$', views.edit_profile),
    url(r'^users/add/?$', views.add_profile),
    url(r'^users/delete/(?P<user_id>[\w\-]+)/?$', views.delete_user),
    url(r'^orders/edit/(?P<order_id>[\w\-]+)/?$', views.edit_order),#{10}
    url(r'^charges/edit/(?P<charge_id>[\w\-]+)/?$', views.edit_charge),#{10}
    url(r'^orders/charges/edit/(?P<charge_id>[\w\-]+)/?$', views.edit_order_charge),#{10}
    url(r'^users/edit/(?P<user_id>[\w\-]+)/?$', views.edit_profiles),
    url(r'^property/edit/(?P<property_id>[\w\-]+)/?$', views.edit_property),
    url(r'^service/types/edit/(?P<service_id>[\w\-]+)/?$', views.edit_service),
    url(r'^resident/edit/(?P<resident_id>[\w\-]+)/?$', views.edit_residents),
    url(r'^contract/edit/(?P<contract_id>[\w\-]+)/?$', views.edit_contract),
    url(r'^service/types/add/?$', views.add_service),
    url(r'^payment/download/xls/?$', views.excel_bank_export),
    # (?P<path>.*)$

]

rentyapp/rentyapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^board/', include('board.urls')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    #url(r'^explorer/', include('explorer.urls')),
]

rentyapp/board/forms.py
from django import forms
from django.forms import ModelForm

from .models import Users, Orders, Charges, OrderCharges, Properties, ServiceTypes, Residents, Contracts


class search_form(forms.Form):
    search_query = forms.CharField(max_length=100, required=True)


class user_form(ModelForm):
    admin = forms.BooleanField(required=False)

    class Meta:
        model = Users

        fields = ['name', 'last_name', 'email', 'provider', 'admin']
        # error_messages = {'field': {'required':''}}

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'provider': forms.TextInput(attrs={'class': 'form-control'}),

        }




class order_form(ModelForm):
    # status = forms.BooleanField(required=False)

    class Meta:
        model = Orders

        fields = ['provider', 'amount', 'file', 'comment', 'code', 'token']
        #error_messages = {'provider': {'required':'Select provider'}}

        widgets = {
            'provider': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.TextInput(attrs={'class': 'form-control'}),
            'file': forms.TextInput(attrs={'class': 'form-control'}),
            'comment': forms.TextInput(attrs={'class': 'form-control'}),
            'code': forms.TextInput(attrs={'class': 'form-control'}),
            'token': forms.TextInput(attrs={'class': 'form-control'}),

        }

class charge_form(ModelForm):

    #status = forms.BooleanField(required=False)

    class Meta:
        model = Charges

        fields = ['contract', 'amount', 'status', 'current_value', 'readjustment', 'pay_date']
        # error_messages = {'field': {'required':''}}

        widgets = {
            'contract': forms.Select(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'current_value': forms.NumberInput(attrs={'class': 'form-control'}),
            'readjustment': forms.TextInput(attrs={'class': 'form-control'}),
            'pay_date': forms.TextInput(attrs={'class': 'form-control'}),


        }

class order_charge_form(ModelForm):

    class Meta:
        model = OrderCharges

        fields = ['charge', 'order', 'amount']
        # error_messages = {'field': {'required':''}}

        widgets = {
            'charge': forms.Select(attrs={'class': 'form-control'}),
            'amount': forms.TextInput(attrs={'class': 'form-control'}),
            'order': forms.Select(attrs={'class': 'form-control'}),

        }

class property_form(ModelForm):

    class Meta:

        model = Properties

        fields = ['category','owner','region','commune',
                  'street','street_number','property_number',
                  'size','name_concierge','phone_concierge']

        #error_messages = {'street': {'max_length':'Street name is longer than 100 characters'}}

        widgets = {
            'owner': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'region': forms.Select(attrs={'class': 'form-control'}),
            'commune': forms.Select(attrs={'class': 'form-control'}),
            'street': forms.TextInput(attrs={'class': 'form-control'}),
            'street_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'property_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'size': forms.NumberInput(attrs={'class': 'form-control'}),
            'name_concierge': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_concierge': forms.TextInput(attrs={'class': 'form-control'}),

        }


class service_form(ModelForm):

    #state = forms.BooleanField(required=False)
    #state = forms.TypedChoiceField(coerce=lambda x: x == 'True', choices=((False, 'No'), (True, 'Yes')))
    #state = forms.BooleanField(widget=forms.CheckboxInput, default=False)

    class Meta:

        model = ServiceTypes

        fields = ['name','state',]

        #error_messages = {'street': {'max_length':'Street name is longer than 100 characters'}}

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

class resident_form(ModelForm):

    #status = forms.BooleanField(required=False)

    class Meta:
        model = Residents

        fields = ['name', 'last_name', 'rut', 'email', 'phone', 'score','user',]
        # error_messages = {'field': {'required':''}}

        widgets = {
            'user': forms.Select(attrs={'class': 'form-control'}),
            'score': forms.NumberInput(attrs={'class': 'form-control'}),
            'phone': forms.NumberInput(attrs={'class': 'form-control'}),
            'rut': forms.NumberInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),


        }

class contract_form(ModelForm):

    #status = forms.BooleanField(required=False)

    class Meta:
        model = Contracts

        fields = ['pay_day', 'start_rent', 'end_rent', 'contract_period', 'property', 'resident']
        # error_messages = {'field': {'required':''}}

        widgets = {
            'resident': forms.Select(attrs={'class': 'form-control'}),
            'contract_period': forms.TextInput(attrs={'class': 'form-control'}),
            'start_rent': forms.TextInput(attrs={'class': 'form-control'}),
            'end_rent': forms.TextInput(attrs={'class': 'form-control'}),
            'pay_day': forms.NumberInput(attrs={'class': 'form-control'}),
            'property': forms.Select(attrs={'class': 'form-control'}),


        }

class login_form(forms.Form):

    email = forms.EmailField(
        max_length=100,
        label="Email",
        required=True,
        error_messages={
            'required': 'Por favor ingrese un email',
            'invalid': 'Por favor ingrese un email valido'}
    )

    password = forms.CharField(
        max_length=15,
        label=u"Contraseña",
        required=True,
        error_messages={
            'required': 'Por favor ingrese su contraseña'}
    )

    def clean_email(self):
        return self.cleaned_data['email'].lower()

rentyapp/templates/v3/dashboard/users/add_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png"
          href="/static/v3/media/website/logo-solo-cb7b48d8befc7c0b5d7f7bd44c8d69ffeed06130a5646ea7a09bb0b57a29b1ed.png"
          sizes="16x16">

    <title>Dashboard Renty</title>
    {% include "v3/dashboard/imports/css.html" %}
    <!-- Custom styles for this template -->

</head>

<body>
{% csrf_token %}
{% include "v3/dashboard/imports/header.html" %}

<div class="container-fluid">
    <div class="row">

        {% include "v3/dashboard/imports/menu.html" %}

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3 mt-4" role="main">

            <ol class="breadcrumb">
                <li class="breadcrumb-item">Profile</li>
                <li class="breadcrumb-item active">Add </li>
            </ol>
            {% if saved %}
            <div class="alert alert-success" role="alert">
                information was saved, correctly !
            </div>
            {% endif %}

            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% for error in field.errors %}
                {{error}}<BR>
                {% endfor %}
                {% endfor %}
            </div>
            {% endif %}


            <!-- Profile Edit -->

            <table width="605" border="0" cellspacing="0" cellpadding="0" class="table table-bordered table-striped">
                <tbody>
                <tr>
                    <td width="605">
                        <strong>Profile Information</strong>
                    </td>
                </tr>
                <tr>
                    <td>

                        <div class="container">
                            <form method="post">
                                {% csrf_token %}

                                {% for field in form %}

                                <!-- Field  {{ field.label }} -->
                                <div class="form-group row">
                                    <label for="{{ field.auto_id }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                                    <div class="col-sm-10">
                                        {{ field }}
                                    </div>
                                </div>

                                {% endfor %}

                                <div class="form-group row">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-success">Save</button>
                                        <a href="/board/main/" class="btn btn-light">Cancel</a>
                                    </div>

                                </div>


                            </form>
                        </div>

                    </td>
                </tr>


                </tbody>
            </table>


            <!-- -->

        </main>
    </div>
</div>

{% include "v3/dashboard/imports/js.html" %}


</body>
</html>

rentyapp/templates/v3/dashboard/users/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png"
          href="/static/v3/media/website/logo-solo-cb7b48d8befc7c0b5d7f7bd44c8d69ffeed06130a5646ea7a09bb0b57a29b1ed.png"
          sizes="16x16">

    <title>Dashboard Renty</title>
    {% include "v3/dashboard/imports/css.html" %}
    <!-- Custom styles for this template -->

</head>

<body>
{% csrf_token %}
{% include "v3/dashboard/imports/header.html" %}

<div class="container-fluid">
    <div class="row">

        {% include "v3/dashboard/imports/menu.html" %}

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3 mt-4" role="main">

            <ol class="breadcrumb">
                <li class="breadcrumb-item">Profile</li>
                <li class="breadcrumb-item active">Modify / {{user.name}} {{user.last_name}}</li>
            </ol>
            {% if saved %}
            <div class="alert alert-success" role="alert">
                "{{user.name}} {{user.last_name}}" information was modified, correctly !
            </div>
            {% endif %}

            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% for error in field.errors %}
                {{error}}<BR>
                {% endfor %}
                {% endfor %}
            </div>
            {% endif %}


            <!-- Profile Edit -->

            <table width="605" border="0" cellspacing="0" cellpadding="0" class="table table-bordered table-striped">
                <tbody>
                <tr>
                    <td width="605">
                        <strong>Profile Information</strong>
                    </td>
                </tr>
                <tr>
                    <td>

                        <div class="container">
                            <form method="post">
                                {% csrf_token %}

                                {% for field in form %}

                                <!-- Field  {{ field.label }} -->
                                <div class="form-group row">
                                    <label for="{{ field.auto_id }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                                    <div class="col-sm-10">
                                        {{ field }}
                                    </div>
                                </div>

                                {% endfor %}

                                <div class="form-group row">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-success">Save</button>
                                        <a href="/board/main/" class="btn btn-light">Cancel</a>
                                    </div>

                                </div>


                            </form>
                        </div>

                    </td>
                </tr>


                </tbody>
            </table>


            <!-- -->

        </main>
    </div>
</div>

{% include "v3/dashboard/imports/js.html" %}


</body>
</html>

rentyapp/templates/v3/dashboard/users/edit_profiles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png"
          href="/static/v3/media/website/logo-solo-cb7b48d8befc7c0b5d7f7bd44c8d69ffeed06130a5646ea7a09bb0b57a29b1ed.png"
          sizes="16x16">

    <title>Dashboard Renty</title>
    {% include "v3/dashboard/imports/css.html" %}
    <!-- Custom styles for this template -->

</head>

<body>
{% csrf_token %}
{% include "v3/dashboard/imports/header.html" %}

<div class="container-fluid">
    <div class="row">

        {% include "v3/dashboard/imports/menu.html" %}

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3 mt-4" role="main">

            <ol class="breadcrumb">
                <li class="breadcrumb-item">Users</li>
                <li class="breadcrumb-item active">Modify / {{user_edit.name}} {{user_edit.last_name}}</li>
            </ol>
            {% if saved %}
            <div class="alert alert-success" role="alert">
                "{{user_edit.name}} {{user_edit.last_name}}" information was modified, correctly !
            </div>
            {% endif %}

            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% for error in field.errors %}
                {{error}}<BR>
                {% endfor %}
                {% endfor %}
            </div>
            {% endif %}


            <!-- Profile Edit -->

            <table width="605" border="0" cellspacing="0" cellpadding="0" class="table table-bordered table-striped">
                <tbody>
                <tr>
                    <td width="605">
                        <strong>User Information</strong>
                    </td>
                </tr>
                <tr>
                    <td>

                        <div class="container">
                            <form method="post">
                                {% csrf_token %}

                                {% for field in form %}

                                <!-- Field  {{ field.label }} -->
                                <div class="form-group row">
                                    <label for="{{ field.auto_id }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                                    <div class="col-sm-10">
                                        {{ field }}
                                    </div>
                                </div>

                                {% endfor %}

                                <div class="form-group row">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-success">Save</button>
                                        <a href="/board/users/" class="btn btn-light">Cancel</a>
                                    </div>

                                </div>


                            </form>
                        </div>

                    </td>
                </tr>


                </tbody>
            </table>


            <!-- -->

        </main>
    </div>
</div>

{% include "v3/dashboard/imports/js.html" %}


</body>
</html>

rentyapp/templates/v3/dashboard/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include "v3/dashboard/imports/css.html" %}
    <style>
        body {
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #eee;
}

.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .form-signin-heading,
.form-signin .checkbox {
  margin-bottom: 10px;
}
.form-signin .checkbox {
  font-weight: normal;
}
.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
    </style>
</head>

<body>
{% include "v3/dashboard/imports/header.html" %}

<div class="container " style="margin-top: 50px;">

    <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        {% csrf_token %}

        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% for error in field.errors %}
            {{error}}<BR>
            {% endfor %}
            {% endfor %}
        </div>
        {% endif %}

        {% if message == True %}
        <div class="alert alert-danger" role="alert"> Email o clave son incorrectos, intente nuevamente </div>
        {% endif %}
        <label for="id_email" class="sr-only">Email address</label>
        <input type="email" id="id_email" class="form-control" placeholder="Email address" required autofocus>
        <label for="id_password" class="sr-only">Password</label>
        <input type="password" id="id_password" class="form-control" placeholder="Password" required>
        <!-- <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div> -->
        <button class="btn btn-lg btn-success btn-block" type="submit">Login</button>
    </form>

    {% include "v3/dashboard/imports/js.html" %}

</body>
</html>

rentyapp/templates/v3/dashboard/users/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png"
          href="/static/v3/media/website/logo-solo-cb7b48d8befc7c0b5d7f7bd44c8d69ffeed06130a5646ea7a09bb0b57a29b1ed.png"
          sizes="16x16">

    <title>Dashboard Renty</title>
    {% include "v3/dashboard/imports/css.html" %}
    <!-- Custom styles for this template -->

</head>

<body>
{% csrf_token %}
{% include "v3/dashboard/imports/header.html" %}

<div class="container-fluid">
    <div class="row">

        {% include "v3/dashboard/imports/menu.html" %}

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3 mt-4" role="main">

            <ol class="breadcrumb">
                <li class="breadcrumb-item">Account Book</li>
                <li class="breadcrumb-item active">Users</li>
            </ol>

            <div class="mb-3">
            <a href="/board/users/add/" class="btn btn-success">+ Add New</a>
            </div>


            <!-- Modems -->

            <form method="get">

                <div class="form-row mb-3">
                    <div class="col-7">
                        <input type="text" class="form-control" id="id_query" name="query" placeholder="Name, Email">
                    </div>
                    <button type="submit" class="btn btn-success">Go</button>
                </div>

                <!-- Query Failed No Rows -->
                {% if query %}
                <div class="alert alert-danger" role="alert"> No results match your query.</div>
                {% endif %}

            </form>

            {% if users %}


            <table class="table table-bordered">
                <tr>
                    <td bgcolor="#F5F5F5">#</td>
                    <td bgcolor="#F5F5F5"><strong>Names</strong></td>
                    <td bgcolor="#F5F5F5"><strong>email</strong></td>
                    <td bgcolor="#F5F5F5"><strong>Created</strong></td>
                    <td bgcolor="#F5F5F5"><strong>Updated</strong></td>
                    <td bgcolor="#F5F5F5"><strong>Provider</strong></td>
                    <td bgcolor="#F5F5F5"><strong>Settings</strong></td>

                </tr>
                {% for user_element in users%}
                <tr id="row-{{user_element.id}}">
                    <td align="center">
                        {{user_element.id}}
                    </td>
                    <td align="left">
                        {{user_element.name}} {{user_element.last_name}}
                        {% if user_element.admin %}<BR>
                        <div class="badge badge-pill badge-success">Admin</div>
                        {% endif %}
                    </td>
                    <td align="left">
                        {{user_element.email}}
                    </td>
                    <td align="left">
                        {{user_element.created_at}}
                    </td>

                    <td align="left">
                        {{user_element.updated_at}}
                    </td>
                    <td align="center">
                        {{user_element.provider}}
                    </td>


                    <td align="center">
                        <a href="/board/users/edit/{{user_element.id}}/" class="btn btn-success">Edit</a>
                        <a href="{{user_element.id}}" id="delete" class="btn btn-danger">Delete</a>
                    </td>

                </tr>
                {% endfor %}
            </table>
            <!-- History Sent users Pagination -->
            <div style="clear:both;"></div>
            <ul class="pagination">
                {% if users.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ users.previous_page_number }}{{url}}">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
                {% endif %}

                {% if users.number|add:'-4' > 1 %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ users.number|add:'-5' }}{{url}}">&hellip;</a>
                </li>
                {% endif %}

                {% for i in users.paginator.page_range %}
                {% if users.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ i }}{{url}}">{{ i }}</a>
                </li>
                {% elif i > users.number|add:'-5' and i < users.number|add:'5' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}{{url}}">{{ i }}</a>
                </li>
                {% endif %}
                {% endfor %}

                {% if users.paginator.num_pages > users.number|add:'4' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ users.number|add:'5' }}{{url}}">&hellip;</a>
                </li>
                {% endif %}

                {% if users.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ users.next_page_number }}{{url}}">Next</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Next</a>
                </li>
                {% endif %}
                <!-- -->


            </ul>
            <!-- History Sent users Pagination -->
            {% else %}
            <center>
                <div class="alert alert-warning" role="alert">
                    No users Registered, So far :(
                </div>
            </center>
            {% endif %}

            <!-- -->

        </main>
    </div>
</div>

{% include "v3/dashboard/imports/js.html" %}

<script>

$(document).ready(function() {

  $('a#delete').click(function(e) {

    var anchor = this;
    $('#deleteModal').modal({
        backdrop: 'static',
        keyboard: false,
        show: true
    });

    $('#ajax_response').html('Are you sure you want to delete this user profile from database?');

    $('button#confirm').click(function(e) {

    $('#ajax_response').html('<div style="text-align:center;"><img src="/static/v3/media/website/loading.gif" width="10%"><BR> Deleting please wait...</div>');

      var id_user = $(anchor).attr('href') //$(this).attr('data-id');

      $.ajax({
        url: "/board/users/delete/" + id_user + '/',
        type: "GET",
        dataType: 'json',
        success: function(data, textStatus, jqXHR) {
          $('#ajax_response').html('');
          $('#ajax_response').html('<div class="alert alert-primary" role="alert">User has been deleted</div>');
          $('#deleteModal').modal('hide');
          $('#row-'+id_user).slideUp();
        },
        error: function(jqXHR, textStatus, errorThrown) {
          $('#ajax_response').html('');
          $('#ajax_response').html('<div class="alert alert-danger" role="alert">User could not be deleted, Please try again later.</div>');
        }
      });

    });
    return false;
  });

});



</script>


<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete confirmation</h5>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>-->
            </div>
            <div class="modal-body">
                <div id="ajax_response"></div>

            </div>
            <div class="modal-footer">
                <button type="button" id="confirm" class="btn btn-danger">Yes, Delete this</button>
                <button type="button" id="cancel" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

            </div>
        </div>
    </div>
</div>


</body>
</html>